[profile.default]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
via-ir = true
solc = "0.8.26" # Add your specific compiler version here
fs_permissions = [{ access = "read-write", path = "./" }]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "solidity-bytes-utils/=lib/solidity-bytes-utils/contracts/",
    "erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/",
    "forge-std/=lib/forge-std/src/",
    "halmos-cheatcodes/=lib/openzeppelin-contracts/lib/halmos-cheatcodes/src/",
    "@solady/=lib/solady/src/"
]
[profile.local]
src = "src"
out = "out"
libs = ["lib"]
optimizer = false
via-ir = true
debug = true
gas_reports = ["OrderBook", "GTXRouter", "PoolManager", "BalanceManager"]
gas_snapshot_emit = false

[rpc_endpoints]
default_network = "http://127.0.0.1:8545"
crossChain = "http://127.0.0.1:8546"
gtxSepolia = "https://anvil.gtxdex.xyz"
riseSepolia = "${RISE_SEPOLIA_ENDPOINT}"
pharos = "https://devnet.dplabs-internal.com"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
arbitrumSepolia = "https://arb-sepolia.g.alchemy.com/v2/jBG4sMyhez7V13jNTeQKfVfgNa54nCmF"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
arbitrum = { key = "${ETHERSCAN_API_KEY}" }
arbitrumSepolia = { key = "${ETHERSCAN_API_KEY}" }
riseSepolia = { key = "" }

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 120
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
single_line_statement_blocks = "multi"
sort_imports = true

[profile.verification]
verifier = "blockscout"
verifier-url = "https://testnet-explorer.riselabs.xyz/api/"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
